"""Updated schema

Revision ID: 1751e0f6b4e4
Revises: df51d7376f34
Create Date: 2025-05-13 07:46:39.821168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1751e0f6b4e4'
down_revision = 'df51d7376f34'
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraint on complaint.order_id
    op.drop_constraint('complaint_ibfk_3', 'complaint', type_='foreignkey')

    # Change complaint.order_id to String(64)
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('order_id',
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=64),
            existing_nullable=True
        )

    # Re-create the foreign key constraint
    op.create_foreign_key(
        'complaint_ibfk_3', 'complaint', 'order', ['order_id'], ['id']
    )

    # Add the code column as nullable
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=8), nullable=True))

    # Populate the code column for existing restaurants (e.g., KFC)
    op.execute(
        "UPDATE restaurant SET code = UPPER(LEFT(name, 1)) WHERE code IS NULL"
    )

    # Now make the column non-nullable and unique
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('code', existing_type=sa.String(length=8), nullable=False)
        batch_op.create_unique_constraint('uq_restaurant_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint('uq_restaurant_code', type_='unique')
        batch_op.drop_column('code')

    op.drop_constraint('complaint_ibfk_3', 'complaint', type_='foreignkey')
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('order_id',
            existing_type=sa.String(length=64),
            type_=mysql.INTEGER(),
            existing_nullable=True
        )
    op.create_foreign_key(
        'complaint_ibfk_3', 'complaint', 'order', ['order_id'], ['id']
    )

    # ### end Alembic commands ###
