"""Updated schema

Revision ID: 63c261580b0b
Revises: 1751e0f6b4e4
Create Date: 2025-05-14 00:26:58.199820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63c261580b0b'
down_revision = '1751e0f6b4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=False))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
