"""Updated schema

Revision ID: df51d7376f34
Revises: 174fbaf44981
Create Date: 2025-05-13 07:39:07.218178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df51d7376f34'
down_revision = '174fbaf44981'
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraints first
    op.drop_constraint('complaint_ibfk_3', 'complaint', type_='foreignkey')
    op.drop_constraint('payment_ibfk_1', 'payment', type_='foreignkey')

    # Alter the columns
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # Re-create the foreign key constraints
    op.create_foreign_key('payment_ibfk_1', 'payment', 'order', ['order_id'], ['id'])
    op.create_foreign_key('complaint_ibfk_3', 'complaint', 'order', ['order_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key('payment_ibfk_1', 'order', ['order_id'], ['id'])
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_foreign_key('complaint_ibfk_3', 'order', ['order_id'], ['id'])
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
